language: c

os:
  - linux
  - osx

env:
  matrix:
    - export NODE_VERSION="5"
    - export NODE_VERSION="4"
    - export NODE_VERSION="0.12"

matrix:
  fast_finish: true

before_install:
  - echo $TRAVIS_OS_NAME
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

before_script:
  - if [ ${NODE_VERSION} = "5" ]; then npm install -g npm; fi
  - npm -v
  - 'npm install -g git://github.com/tars/tars-cli.git#${TRAVIS_COMMIT}'

script:
  - tars --version
  - mkdir tars-temp
  - cd tars-temp
  - tars init --silent -s https://github.com/tars/tars/archive/version-1.6.0.zip
  - tars start re-init --flags '--silent'
  - tars add-module new -e
  - tars add-module new_ --empty
  - tars add-module new1 -f
  - tars add-module new1_ --full
  - tars add-module new2 -b
  - tars add-module new2_ --basic
  - tars add-module new3 -a
  - tars add-module new3_ --assets
  - tars add-module new4 -i
  - tars add-module new4_ --ie
  - tars add-module new5 -d
  - tars add-module new5_ --data
  - tars add-module new6 -t
  - tars add-module new6_ --template
  - tars add-page main.html
  - tars add-page inner
  - tars add-page contacts -e
  - tars add-page contacts_ --empty
  - tars build --release --ie
